# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: check-added-large-files
    # - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    # - id: pretty-format-json
    - id: trailing-whitespace
      exclude_types:
        - javascript
        - markdown
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear==22.8.23
        - flake8-noqa==1.2.9
      args:
      - --max-line-length=120
      - --max-complexity=18
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.10
      args:
        - --line-length=120
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies:
          - tokenize-rt==3.2.0
          - types-redis
          - types-PyYAML
          - SQLAlchemy-stubs
          - types-Flask-SQLAlchemy
          - types-Flask-Cors
          - types-Flask
